### ISSUE TITLE
Tableschema failed validation only occurs on HTTP request and does not print errors.

### ISSUE THREAD

**Issue by loganripplinger** [brighthive/data-resource-api#40]
Current
If your table schema in your descriptor file does not pass validation in the resource handler it raises an unhandled error that only occurs when interacting with the API via an HTTP method.

Here is the output

```data-resource-api_1   | 2019-12-11 19:18:39,102 - data-model-manager - ERROR - Encountered an error while processing a request.
data-resource-api_1   | Traceback (most recent call last):
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
data-resource-api_1   |     rv = self.dispatch_request()
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
data-resource-api_1   |     return self.view_functions[rule.endpoint](**req.view_args)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
data-resource-api_1   |     resp = resource(*args, **kwargs)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
data-resource-api_1   |     return self.dispatch_request(*args, **kwargs)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
data-resource-api_1   |     resp = meth(*args, **kwargs)
data-resource-api_1   |   File "/data-resource/data_resource_api/api/core/versioned_resource.py", line 171, in post
data-resource-api_1   |     return self.get_resource_handler(request.headers).insert_one(self.data_model, self.data_resource_name, self.table_schema, request)
data-resource-api_1   |   File "/data-resource/data_resource_api/api/v1_0_0/resource_handler.py", line 262, in insert_one
data-resource-api_1   |     if not validate(table_schema):
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/validate.py", line 16, in validate
data-resource-api_1   |     Schema(descriptor, strict=True)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/schema.py", line 41, in __init__
data-resource-api_1   |     self.__build()
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/schema.py", line 255, in __build
data-resource-api_1   |     raise exception
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/schema.py", line 250, in __build
data-resource-api_1   |     self.__profile.validate(self.__current_descriptor)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/profile.py", line 64, in validate
data-resource-api_1   |     raise exceptions.ValidationError(message, errors=errors)
data-resource-api_1   | tableschema.exceptions.ValidationError: There are 1 validation errors (see exception.errors)
data-resource-api_1   | 2019-12-11 19:18:39,102 - data-model-manager - ERROR - Encountered an error while processing a request.
data-resource-api_1   | Traceback (most recent call last):
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
data-resource-api_1   |     rv = self.dispatch_request()
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
data-resource-api_1   |     return self.view_functions[rule.endpoint](**req.view_args)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
data-resource-api_1   |     resp = resource(*args, **kwargs)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
data-resource-api_1   |     return self.dispatch_request(*args, **kwargs)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
data-resource-api_1   |     resp = meth(*args, **kwargs)
data-resource-api_1   |   File "/data-resource/data_resource_api/api/core/versioned_resource.py", line 171, in post
data-resource-api_1   |     return self.get_resource_handler(request.headers).insert_one(self.data_model, self.data_resource_name, self.table_schema, request)
data-resource-api_1   |   File "/data-resource/data_resource_api/api/v1_0_0/resource_handler.py", line 262, in insert_one
data-resource-api_1   |     if not validate(table_schema):
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/validate.py", line 16, in validate
data-resource-api_1   |     Schema(descriptor, strict=True)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/schema.py", line 41, in __init__
data-resource-api_1   |     self.__build()
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/schema.py", line 255, in __build
data-resource-api_1   |     raise exception
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/schema.py", line 250, in __build
data-resource-api_1   |     self.__profile.validate(self.__current_descriptor)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/tableschema/profile.py", line 64, in validate
data-resource-api_1   |     raise exceptions.ValidationError(message, errors=errors)
data-resource-api_1   | tableschema.exceptions.ValidationError: There are 1 validation errors (see exception.errors)
data-resource-api_1   | 
data-resource-api_1   | During handling of the above exception, another exception occurred:
data-resource-api_1   | 
data-resource-api_1   | Traceback (most recent call last):
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
data-resource-api_1   |     self.handle_request(listener_name, req, client, addr)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
data-resource-api_1   |     addr)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
data-resource-api_1   |     respiter = self.wsgi(environ, resp.start_response)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
data-resource-api_1   |     return self.wsgi_app(environ, start_response)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
data-resource-api_1   |     response = self.handle_exception(e)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
data-resource-api_1   |     return original_handler(e)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
data-resource-api_1   |     reraise(exc_type, exc_value, tb)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
data-resource-api_1   |     raise value.with_traceback(tb)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
data-resource-api_1   |     response = self.full_dispatch_request()
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
data-resource-api_1   |     rv = self.handle_user_exception(e)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
data-resource-api_1   |     return original_handler(e)
data-resource-api_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
data-resource-api_1   |     return handler(e)
data-resource-api_1   |   File "/data-resource/data_resource_api/app/exception_handler.py", line 92, in handle_errors
data-resource-api_1   |     return e.get_response()
data-resource-api_1   | AttributeError: 'ValidationError' object has no attribute 'get_response'
```

Expected
We should handle it somehow and print the errors.
We should probably run the check on load.

**Comment by loganripplinger** [comment]
If I modify the exception class to this,

```
    try:
        message = e.get_response()
    except AttributeError:
        logger.info(e.errors)
        message = json.dumps({'error': 'Unhandled error.'})
    return message
```

I get this output at the end,

```
data-resource-api_1   | 2019-12-11 19:18:39,104 - data-model-manager - INFO - [ValidationError('Descriptor validation error: [] is too short at "foreignKeys" in descriptor and at "properties/foreignKeys/minItems" in profile')]
data-resource-api_1   | 2019-12-11 19:18:39,104 - data-model-manager - INFO - [ValidationError('Descriptor validation error: [] is too short at "foreignKeys" in descriptor and at "properties/foreignKeys/minItems" in profile')]
```
